trigger1/urls.py
from django.urls import path
from trigger1.views import login_user, logout_user
from trigger1.views import register, register_manajer_penonton, register_panitia
from trigger1.views import show_home, show_dashboard, show_dashboard_manajer

app_name = 'trigger1'

urlpatterns = [
    path('', show_home, name='home'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('register-manajer-penonton/', register_manajer_penonton, name='register-manajer-penonton'),
    path('register-panitia/', register_panitia, name='register-panitia'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('dashboard-manajer/', show_dashboard_manajer, name='dashboard-manajer'),
]

uleague/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger1/', include('trigger1.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger6/', include('trigger6.urls')),
]

trigger1/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User

# Create your models here.
class User(AbstractUser):
    is_manajer = models.BooleanField(default=False)
    is_penonton = models.BooleanField(default=False)
    is_panitia = models.BooleanField(default=False)

    # class Role(models.TextChoices):
    #     MANAJER = "MANAJER", 'Manajer'
    #     PENONTON = "PENONTON", 'Penonton'
    #     PANITIA = "PANITIA", 'Panitia'
    
    # role = models.CharField('Role')

trigger1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=50)
    password1 = forms.CharField(max_length=50)
    password2 = forms.CharField(max_length=50)
    
class RegisterForm(UserCreationForm):
    CHOICES = [('Mahasiswa', 'Mahasiswa'), ('Dosen', 'Dosen'), ('Tendik', 'Tendik'), ('Alumni', 'Alumni'), ('Umum', 'Umum'),]

    username = forms.CharField(max_length=50)
    password1 = forms.CharField(max_length=50)
    password2 = forms.CharField(max_length=50)
    nama_depan = forms.CharField(max_length=50)
    nama_belakang = forms.CharField(max_length=50)
    nomor_hp = forms.CharField(max_length=15)
    email = forms.CharField(max_length=50)
    alamat = forms.CharField(max_length=255)
    status = forms.CharField(
        widget=forms.RadioSelect(choices=CHOICES)
    )
    jabatan = forms.CharField(max_length=50, required=False)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'nama_depan', 'nama_belakang', 'nomor_hp', 'email',  'status', 'alamat', 'is_manajer', 'is_penonton', 'is_panitia' )

trigger1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .forms import LoginForm, RegisterForm

def login_user(request):
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password) 
            if user is not None:
                login(request, user) # melakukan login terlebih dahulu
                response = HttpResponseRedirect(reverse("trigger1:dashboard")) # membuat response
                response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
                return response
            else:
                messages.info(request, 'Username atau Password salah!')
        else:
            messages.error(request, 'Form tidak valid')
    context = {
        'form': form,
    }
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('trigger1:login'))
    response.delete_cookie('last_login')
    return response

def register(request):
    context = {
    }
    return render(request, "register/register.html", context)

def register_panitia(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('trigger1:login')
        else:
            messages.error(request, 'Form tidak valid')
    
    context = {'form': form}
    return render(request, 'register/register-panitia.html', context)

def register_manajer_penonton(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('trigger1:login')
        else:
            messages.error(request, 'Form tidak valid')

    context = {'form': form}
    return render(request, 'register/register-manajer-penonton.html', context)

def show_home(request):
    context = {
    }
    return render(request, "home.html", context)

@csrf_exempt
#@login_required(login_url='/trigger1/login/')
def show_dashboard(request):
    context = {
    }
    return render(request, "dashboard/dashboard.html", context)

@csrf_exempt
#@login_required(login_url='/trigger1/login/')
def show_dashboard_manajer(request):
    context = {
    }
    return render(request, "dashboard/dashboard-manajer.html", context)

trigger1/templates/register/register-manajer-penonton.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Register Manajer</title>
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock meta %}

{% block content %}  
<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5 text-center">
                <div class="mb-4">
                  <a href="{% url 'trigger1:home' %}"><img src="/static/img/database.png" width="50" height="auto"></a>
                </div>

                <h2 class="fw-bold mb-2 text-uppercase">Create an account</h2>
                <p class="text-black-50 mb-5">Please enter a new username and a password!</p>

                <form method="POST">
                    {% csrf_token %}  
                    <div class="form-outline mb-4">
                        <input type="text" id="id_username" name="username" maxlength="150" autocapitalize="none" autocomplete="id_username" autofocus required id="id_username" class="form-control form-control-lg" placeholder="Username"/>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="id_password1" name="password1" autocomplete="new-password" required id="id_password1" class="form-control form-control-lg" placeholder="Password"/>
                    </div>

                    <div class="form-outline mb-4">
                        <input type="password" id="id_password2" name="password2" autocomplete="new-password" required id="id_password2" class="form-control form-control-lg" placeholder="Confirm Password"/>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="text" id="id_nama_depan" name="nama_depan" required id="id_nama_depan" class="form-control form-control-lg" placeholder="Nama Depan"/>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="text" id="id_nama_belakang" name="nama_belakang" required id="id_nama_belakang" class="form-control form-control-lg" placeholder="Nama Belakang"/>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="number" id="id_nomor_hp" name="nomor_hp" required id="id_nomor_hp" class="form-control form-control-lg" placeholder="Nomor HP"/>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="text" id="id_email" name="email" required id="id_email" class="form-control form-control-lg" placeholder="Email"/>
                    </div>

                    <div class="form-outline mb-4">
                      <input type="text" id="id_alamat" name="alamat" required id="id_alamat" class="form-control form-control-lg" placeholder="Alamat"/>
                    </div>

                    <div class="d-flex justify-content-center mb-4">
                      {{form.status}}
                    </div>

                    <div class="d-flex justify-content-center">
                        <button type="submit" name="submit" value="Daftar"
                        class="btn btn-outline-secondary">Register</button>
                    </div>

                    <p class="text-center text-muted mt-5 mb-0">Already have an account? <a href="{% url 'trigger1:login' %}"
                        class="fw-bold text-body"><u>Login here</u></a></p>

                </form>
                {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

trigger1/templates/register/register-panitia.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Register Panitia</title>
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock meta %}

{% block content %}  
<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5 text-center">
                <div class="mb-4">
                  <a href="{% url 'trigger1:home' %}"><img src="/static/img/database.png" width="50" height="auto"></a>
                </div>

                <h2 class="fw-bold mb-2 text-uppercase">Create an account</h2>
                <p class="text-black-50 mb-5">Please enter a new username and a password!</p>

                <form method="POST">
                  {% csrf_token %}  
                  <div class="form-outline mb-4">
                      <input type="text" id="id_username" name="username" maxlength="150" autocapitalize="none" autocomplete="id_username" autofocus required id="id_username" class="form-control form-control-lg" placeholder="Username"/>
                  </div>

                  <div class="form-outline mb-4">
                      <input type="password" id="id_password1" name="password1" autocomplete="new-password" required id="id_password1" class="form-control form-control-lg" placeholder="Password"/>
                  </div>

                  <div class="form-outline mb-4">
                      <input type="password" id="id_password2" name="password2" autocomplete="new-password" required id="id_password2" class="form-control form-control-lg" placeholder="Confirm Password"/>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="text" id="id_nama_depan" name="nama_depan" required id="id_nama_depan" class="form-control form-control-lg" placeholder="Nama Depan"/>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="text" id="id_nama_belakang" name="nama_belakang" required id="id_nama_belakang" class="form-control form-control-lg" placeholder="Nama Belakang"/>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="number" id="id_nomor_hp" name="nomor_hp" required id="id_nomor_hp" class="form-control form-control-lg" placeholder="Nomor HP"/>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="text" id="id_email" name="email" required id="id_email" class="form-control form-control-lg" placeholder="Email"/>
                  </div>

                  <div class="form-outline mb-4">
                    <input type="text" id="id_alamat" name="alamat" required id="id_alamat" class="form-control form-control-lg" placeholder="Alamat"/>
                  </div>

                  <div class="d-flex justify-content-center mb-4">
                    {{form.status}}
                  </div>

                  <div class="form-outline mb-4">
                    <input type="text" id="id_jabatan" name="jabatan" class="form-control form-control-lg" placeholder="Jabatan"/>
                  </div>

                  <div class="d-flex justify-content-center">
                      <button type="submit" name="submit" value="Daftar"
                      class="btn btn-outline-secondary">Register</button>
                  </div>

                  <p class="text-center text-muted mt-5 mb-0">Already have an account? <a href="{% url 'trigger1:login' %}"
                      class="fw-bold text-body"><u>Login here</u></a></p>

              </form>
                {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

trigger1/templates/register/register.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<title>Register</title>
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock meta %}

{% block content %}  
<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5 text-center">
                <div class="mb-4">
                  <a href="{% url 'trigger1:home' %}"><img src="/static/img/database.png" width="50" height="auto"></a>
                </div>

                <h2 class="fw-bold mb-2 text-uppercase">Create an account</h2>
                <p class="text-black-50 mb-5">Please enter a new username and a password!</p>

                <div class="d-flex justify-content-center">
                  <a class="btn btn-outline-secondary mt-2" style="margin-right: 10px;" href="{% url 'trigger1:register-manajer-penonton' %}" type="button" value="Manajer">Manajer</a> 
                  <a class="btn btn-outline-secondary mt-2" href="{% url 'trigger1:register-manajer-penonton' %}" type="button" value="Penonton">Penonton</a> 
                  <a class="btn btn-outline-secondary mt-2" style="margin-left: 10px;" href="{% url 'trigger1:register-panitia' %}" type="button" value="Panitia">Panitia</a> 
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock content %}