trigger1/urls.py
from django.urls import path
from trigger1.views import login_user, logout_user
from trigger1.views import register, register_manajer_penonton, register_panitia
from trigger1.views import show_home, show_dashboard, show_dashboard_manajer

app_name = 'trigger1'

urlpatterns = [
    path('', show_home, name='home'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('register-manajer-penonton/', register_manajer_penonton, name='register-manajer-penonton'),
    path('register-panitia/', register_panitia, name='register-panitia'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('dashboard-manajer/', show_dashboard_manajer, name='dashboard-manajer'),
]

trigger5/urls.py
from django.urls import path
from trigger5.views import show_manage_pertandingan, show_peristiwa_tim, mulai_pertandingan, tim1_peristiwa, tim2_peristiwa
from trigger5.views import show_history_rapat, form_isi_rapat, mulai_rapat

app_name = 'trigger5'

urlpatterns = [
    path('manage-pertandingan/', show_manage_pertandingan, name='manage-pertandingan'),
    path('manage-pertandingan/peristiwa-tim/', show_peristiwa_tim, name='peristiwa-tim'),
    path('mulai-pertandingan/', mulai_pertandingan, name='mulai_pertandingan'),
    path('tim1-peristiwa/', tim1_peristiwa, name='tim1_peristiwa'),
    path('tim2-peristiwa/', tim2_peristiwa, name='tim2_peristiwa'),
    path('history-rapat/', show_history_rapat, name='history-rapat'),
    path('form-isi-rapat/', form_isi_rapat, name='form_isi_rapat'),
    path('mulai-rapat/', mulai_rapat, name='mulai_rapat'),
]

uleague/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger1/', include('trigger1.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger6/', include('trigger6.urls')),
]

trigger5/models.py
from django.db import models

# Create your models here.

trigger5/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
#@login_required(login_url='/sepakbola/login/')
def show_manage_pertandingan(request):
    context = {
    }
    return render(request, "manage-pertandingan.html", context)

#@login_required(login_url='/sepakbola/login/')
def show_peristiwa_tim(request):
    context = {
    }
    return render(request, "peristiwa-tim.html", context)

#@login_required(login_url='/sepakbola/login/')
def mulai_pertandingan(request):
  user = request.user
  context = {
    }
  return render(request, "mulai-pertandingan.html", context)

#@login_required(login_url='/sepakbola/login/')
def tim1_peristiwa(request):
  user = request.user
  context = {
    }
  return render(request, "tim1-peristiwa.html", context)

#@login_required(login_url='/sepakbola/login/')
def tim2_peristiwa(request):
  user = request.user
  context = {
    }
  return render(request, "tim2-peristiwa.html", context)

@csrf_exempt
#@login_required(login_url='/sepakbola/login/')
def show_history_rapat(request):
    context = {
    }
    return render(request, "rapat/history-rapat.html", context)

#@login_required(login_url='/sepakbola/login/')
def mulai_rapat(request):
  user = request.user
  context = {
    }
  return render(request, "rapat/mulai-rapat.html", context)

#@login_required(login_url='/sepakbola/login/')
def form_isi_rapat(request):
  user = request.user
  context = {
    }
  return render(request, "rapat/form-isi-rapat.html", context)

trigger5/templates/manage-pertandingan.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Manage Pertandingan</title>
    <link rel="stylesheet" href="{% static 'css/manage_pertandingan.css' %}">
    {% include 'navbar/navbar-panitia.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-9 col-xl-9">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">
                    <h2 class="fw-bold mb-2 text-uppercase">List Pertandingan</h2>

                    <!-- <h2 class="fw-bold mb-2 text-uppercase">PERTANDINGAN BELUM LENGKAP!</h2>
                    <h4 class="fw-bold mb-2 text-uppercase">KLIK TOMBOL NEXT UNTUK MEMBUAT PERTANDINGAN</h2>
                    <a class="btn btn-outline-secondary mt-5" href="{}" type="button" value="Next">Next</a> -->

                    <div id="tableCarousel" class="carousel slide" data-ride="carousel">
                      <div class="carousel-inner">
                          <!-- Case: babak pertama -->
                         <div class="carousel-item active"> 
                          <table class="table table-hover">
                            <thead>
                                <tr>
                                  <th colspan="5">LIST PERTANDINGAN GRUP STAGE</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td><b>Grup</b></td>
                                  <td><b>Tim</b></td>
                                  <td><b>Waktu</b></td>
                                  <td><b>Pemenang</b></td>
                                  <td><b>Action</b></td>
                                </tr>
                                <tr>
                                  <td rowspan="2" style="vertical-align : middle;text-align:center;">A</td>
                                  <td>UI FC VS UGM FC</td>
                                  <td>1 Mei 2023</td>
                                  <td>UGM FC</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Peristiwa Tim 1</button>
                                    <button type="button" class="btn btn-secondary btn-sm">Peristiwa Tim 2</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td>ITB FC VS BINUS FC</td>
                                  <td>3 Mei 2023</td>
                                  <td>BINUS FC</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm btn-block">Peristiwa Tim 1</button>
                                    <button type="button" class="btn btn-secondary btn-sm btn-block">Peristiwa Tim 2</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td rowspan="3" style="vertical-align : middle;text-align:center;">B</td>
                                  <td>UNAIR FC VS UNDIP FC</td>
                                  <td>[Waktu Dimulai -5 Menit]</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-success btn-sm btn-block">Mulai</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td>UNPAD FC VS ITS FC</td>
                                  <td>7 Mei 2023</td>
                                  <td>-</td>
                                  <td>Belum Waktunya</td>
                                </tr>
                                <tr>
                                  <td>UB FC VS UPH FC</td>
                                  <td>9 Mei 2023</td>
                                  <td>-</td>
                                  <td>Belum Waktunya</td>
                                </tr>
                              </tbody>
                          </table>
                         </div>
                         <!-- Case: belum set semua waktu pertandingan -->
                         <div class="carousel-item">
                          <table class="table table-hover">
                            <thead>
                                <tr>
                                  <th colspan="5">LIST PERTANDINGAN GRUP STAGE</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td><b>Grup</b></td>
                                  <td><b>Tim</b></td>
                                  <td><b>Waktu</b></td>
                                  <td><b>Pemenang</b></td>
                                  <td><b>Action</b></td>
                                </tr>
                                <tr>
                                  <td rowspan="2" style="vertical-align : middle;text-align:center;">A</td>
                                  <td>UI FC VS UGM FC</td>
                                  <td>1 Mei 2023</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Update</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td>ITB FC VS BINUS FC</td>
                                  <td>-</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Update</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td rowspan="3" style="vertical-align : middle;text-align:center;">B</td>
                                  <td>UNAIR FC VS UNDIP FC</td>
                                  <td>-</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Update</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td>UNPAD FC VS ITS FC</td>
                                  <td>-</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Update</button>
                                  </td>
                                </tr>
                                <tr>
                                  <td>UB FC VS UPH FC</td>
                                  <td>-</td>
                                  <td>-</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Update</button>
                                  </td>
                                </tr>
                              </tbody>
                          </table>
                         </div>
                         <!-- Case: Sudah ada pemenang akhir -->
                         <div class="carousel-item">
                          <table class="table table-hover">
                            <thead>
                                <tr>
                                  <th colspan="5">LIST PERTANDINGAN FINAL</th>
                                </tr>
                              </thead>
                              <tbody>
                                <tr>
                                  <td><b>Tim</b></td>
                                  <td><b>Waktu</b></td>
                                  <td><b>Pemenang</b></td>
                                  <td><b>Action</b></td>
                                </tr>
                                <tr>
                                  <td>UGM FC VS BINUS FC</td>
                                  <td>1 Juni 2023</td>
                                  <td>UGM FC</td>
                                  <td>
                                    <button type="button" class="btn btn-secondary btn-sm">Peristiwa Tim 1</button>
                                    <button type="button" class="btn btn-secondary btn-sm">Peristiwa Tim 2</button>
                                  </td>
                                </tr>
                              </tbody>
                            </table>

                            <h4 class="fw-bold mb-2 mt-5 text-uppercase">INI AKHIR MUSIM!</h2>
                            <h4 class="fw-bold mb-2 text-uppercase">KLIK TOMBOL NEXT UNTUK MEMBUAT PERTANDINGAN BARU</h2>
                            <a class="btn btn-outline-secondary mt-2" href="{}" type="button" value="Next">Next</a>
                         
                          </div>
                      </div>
                   </div>
                </div>
                  <a class="carousel-control-prev align-self-end" href="#tableCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                  </a>
                  <a class="carousel-control-next align-self-end" href="#tableCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only"></span>
                  </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script type="text/javascript" src="{% static 'js/manage_pertandingan.js' %}"></script>
  {% include 'footer.html' %}
  {% endblock content %}

trigger5/templates/mulai-pertandingan.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Mulai Pertandingan</title>
    <link rel="stylesheet" href="{% static 'css/peminjaman_stadium.css' %}">
    {% include 'navbar/navbar-panitia.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">
                    <h2 class="fw-bold mb-2 text-uppercase">Pertandingan</h2>
                    <p class="text-black-50 mb-5">Gelora Bung Karno | 13 April 2023</p>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                            <th scope="col">Tim 1</th>
                            <th scope="col">Tim 2</th>
                            <th scope="col">Peristiwa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                            <td>BINUS FC</td>
                            <td>UGM FC</td>
                            <td>
                              <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger5:tim1_peristiwa' %}" value="peristiwa1">Masukkan Peristiwa Tim 1</a>
                              <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger5:tim2_peristiwa' %}" value="peristiwa2">Masukkan Peristiwa Tim 2</a>
                            </td>
                            </tr>
                        </tbody>
                    </table>
                    <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger1:dashboard' %}" type="button" value="Submit">Submit</a> 
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
  {% include 'footer.html' %}
  {% endblock content %}

trigger5/templates/peristiwa-tim.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Manage Pertandingan</title>
    <link rel="stylesheet" href="{% static 'css/peminjaman_stadium.css' %}">
    {% include 'navbar/navbar-panitia.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-7 col-lg-6 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">

                    <table class="table table-hover">
                        <thead>
                            <tr>
                              <th colspan="2">Peristiwa Tim UI FC</th>
                            </tr>
                          </thead>
                          <tbody>
                            <tr>
                              <td><b>Nama Pemain</b></td>
                              <td><b>Peristiwa</b></td>
                            </tr>
                            <tr>
                              <td>John Doe</td>
                              <td>assist</td>
                            </tr>
                            <tr>
                              <td>Jingga M</td>
                              <td>gol</td>
                            </tr>
                            <tr>
                              <td>Radit A</td>
                              <td>kartu kuning</td>
                            </tr>
                            <tr>
                              <td>Arya DK</td>
                              <td>kartu kuning</td>
                            </tr>
                            <tr>
                              <td>Daffa F</td>
                              <td>gol</td>
                            </tr>
                          </tbody>
                    </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
  {% include 'footer.html' %}
  {% endblock content %}

trigger5/templates/tim1-peristiwa.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Peristiwa Tim 1</title>
    <link rel="stylesheet" href="">
    {% include 'navbar/navbar-panitia.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">

                    <h2 class="fw-bold mb-2 text-uppercase">Peristiwa Tim 1</h2>
                    <p class="text-black-50 mb-5">Tentukan peristiwa untuk tim: BINUS FC</p>
                    <form method="POST" action="">
                      <table class="table table-hover">
                        <thead>
                            <tr>
                            <th scope="col">Nama Pemain</th>
                            <th scope="col">Peristiwa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                              <td>player 1</td>
                              <td>
                                <div class="dropdown-center">
                                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Assist
                                  </button>
                                  <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">None</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                      <li><a class="dropdown-item" href="#">Goal</a></li>
                                      <li><a class="dropdown-item" href="#">Assist</a></li>
                                  </ul>
                                </div>
                              </td>
                            </tr>
                            <tr>
                              <td>player 2</td>
                              <td>
                                <div class="dropdown-center">
                                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Goal
                                  </button>
                                  <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">None</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                      <li><a class="dropdown-item" href="#">Goal</a></li>
                                      <li><a class="dropdown-item" href="#">Assist</a></li>
                                  </ul>
                                </div>
                              </td>
                              <tr>
                                <td>player 3</td>
                                <td>
                                  <div class="dropdown-center">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        None
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">None</a></li>
                                        <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                        <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                        <li><a class="dropdown-item" href="#">Goal</a></li>
                                        <li><a class="dropdown-item" href="#">Assist</a></li>
                                    </ul>
                                  </div>
                                </td>
                              </tr>
                            </tr>
                        </tbody>
                      </table>
        
                    <button class="btn btn-outline-secondary mt-5" href="{% url 'trigger5:mulai_pertandingan' %}" type="submit" value="Submit">Submit</button>
    
                    </form>  
    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% include 'footer.html' %}
{% endblock content %}

trigger5/templates/tim2-peristiwa.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Peristiwa Tim 2</title>
    <link rel="stylesheet" href="">
    {% include 'navbar/navbar-panitia.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4 pb-5">

                    <h2 class="fw-bold mb-2 text-uppercase">Peristiwa Tim 2</h2>
                    <p class="text-black-50 mb-5">Tentukan peristiwa untuk tim: BINUS FC</p>
                    <form method="POST" action="">
                      <table class="table table-hover">
                        <thead>
                            <tr>
                            <th scope="col">Nama Pemain</th>
                            <th scope="col">Peristiwa</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                              <td>player 1</td>
                              <td>
                                <div class="dropdown-center">
                                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Assist
                                  </button>
                                  <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">None</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                      <li><a class="dropdown-item" href="#">Goal</a></li>
                                      <li><a class="dropdown-item" href="#">Assist</a></li>
                                  </ul>
                                </div>
                              </td>
                            </tr>
                            <tr>
                              <td>player 2</td>
                              <td>
                                <div class="dropdown-center">
                                  <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                      Goal
                                  </button>
                                  <ul class="dropdown-menu">
                                      <li><a class="dropdown-item" href="#">None</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                      <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                      <li><a class="dropdown-item" href="#">Goal</a></li>
                                      <li><a class="dropdown-item" href="#">Assist</a></li>
                                  </ul>
                                </div>
                              </td>
                              <tr>
                                <td>player 3</td>
                                <td>
                                  <div class="dropdown-center">
                                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        None
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="#">None</a></li>
                                        <li><a class="dropdown-item" href="#">Kartu Kuning</a></li>
                                        <li><a class="dropdown-item" href="#">Kartu Merah</a></li>
                                        <li><a class="dropdown-item" href="#">Goal</a></li>
                                        <li><a class="dropdown-item" href="#">Assist</a></li>
                                    </ul>
                                  </div>
                                </td>
                              </tr>
                            </tr>
                        </tbody>
                      </table>
        
                    <button class="btn btn-outline-secondary mt-5" href="{% url 'trigger5:mulai_pertandingan' %}" type="submit" value="Submit">Submit</button>
    
                    </form>  
    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <script type="text/javascript" src="{% static 'js/login.js' %}"></script>
{% include 'footer.html' %}
{% endblock content %}