trigger1/urls.py
from django.urls import path
from trigger1.views import login_user, logout_user
from trigger1.views import register, register_manajer_penonton, register_panitia
from trigger1.views import show_home, show_dashboard, show_dashboard_manajer

app_name = 'trigger1'

urlpatterns = [
    path('', show_home, name='home'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name='register'),
    path('register-manajer-penonton/', register_manajer_penonton, name='register-manajer-penonton'),
    path('register-panitia/', register_panitia, name='register-panitia'),
    path('dashboard/', show_dashboard, name='dashboard'),
    path('dashboard-manajer/', show_dashboard_manajer, name='dashboard-manajer'),
]

trigger3/urls.py
from django.urls import path
from trigger3.views import show_peminjaman_stadium, show_form_peminjaman_stadium, show_list_waktu_stadium

app_name = 'trigger3'

urlpatterns = [
    path('peminjaman-stadium/', show_peminjaman_stadium, name='peminjaman-stadium'),
    path('form-peminjaman-stadium/', show_form_peminjaman_stadium, name='form-peminjaman-stadium'),
    path('waktu-stadium/', show_list_waktu_stadium, name='waktu-stadium'),
]

trigger4/urls.py
from django.urls import path
from trigger4.views import show_list_pertandingan, show_pembuatan_pertandingan, show_form_pembuatan_pertandingan, show_form_pemilihan_jadwal

app_name = 'trigger4'

urlpatterns = [
    path('list-pertandingan/', show_list_pertandingan, name='list-pertandingan'),
    path('pembuatan-pertandingan/', show_pembuatan_pertandingan, name='pembuatan-pertandingan'),
    path('pembuatan-pertandingan/form-pembuatan-pertandingan/', show_form_pembuatan_pertandingan, name='form-pembuatan-pertandingan'),
    path('pembuatan-pertandingan/form-pemilihan-jadwal/', show_form_pemilihan_jadwal, name='form-pemilihan-jadwal'),
]

trigger5/urls.py
from django.urls import path
from trigger5.views import show_manage_pertandingan, show_peristiwa_tim, mulai_pertandingan, tim1_peristiwa, tim2_peristiwa
from trigger5.views import show_history_rapat, form_isi_rapat, mulai_rapat

app_name = 'trigger5'

urlpatterns = [
    path('manage-pertandingan/', show_manage_pertandingan, name='manage-pertandingan'),
    path('manage-pertandingan/peristiwa-tim/', show_peristiwa_tim, name='peristiwa-tim'),
    path('mulai-pertandingan/', mulai_pertandingan, name='mulai_pertandingan'),
    path('tim1-peristiwa/', tim1_peristiwa, name='tim1_peristiwa'),
    path('tim2-peristiwa/', tim2_peristiwa, name='tim2_peristiwa'),
    path('history-rapat/', show_history_rapat, name='history-rapat'),
    path('form-isi-rapat/', form_isi_rapat, name='form_isi_rapat'),
    path('mulai-rapat/', mulai_rapat, name='mulai_rapat'),
]

uleague/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger1/', include('trigger1.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger6/', include('trigger6.urls')),
]

templates/navbar/navbar-manajer.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background-color: #f4f5f0">
    <div class="container-fluid">
      <a class="navbar-brand p-2" href="{% url 'trigger1:dashboard' %}"><img src="/static/img/database.png" width="30" height="auto"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">mengelola tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger3:peminjaman-stadium' %}">peminjaman stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger4:list-pertandingan' %}">list pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger5:history-rapat' %}">history rapat</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              account
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">profile</a></li>
              <li><a class="dropdown-item" href="{% url 'trigger1:logout' %}">logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/navbar/navbar-panitia.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background-color: #f4f5f0">
    <div class="container-fluid">
      <a class="navbar-brand p-2" href="{% url 'trigger1:dashboard' %}"><img src="/static/img/database.png" width="30" height="auto"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">rapat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">manage pertandingan</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              account
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">profile</a></li>
              <li><a class="dropdown-item" href="{% url 'trigger1:logout' %}">logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/navbar/navbar-penonton.html
{% load static %}

<nav class="navbar navbar-expand-lg" style="background-color: #f4f5f0">
    <div class="container-fluid">
      <a class="navbar-brand p-2" href="{% url 'trigger1:dashboard' %}"><img src="/static/img/database.png" width="30" height="auto"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">pembelian tiket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">list pertandingan</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              account
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">profile</a></li>
              <li><a class="dropdown-item" href="{% url 'trigger1:logout' %}">logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/navbar/navbar.html

<nav class="navbar navbar-expand-lg" style="background-color: #f4f5f0">
    <div class="container-fluid">
      <a class="navbar-brand p-2" href="{% url 'trigger1:dashboard' %}"><img src="/static/img/database.png" width="30" height="auto"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trigger1:dashboard' %}">dashboard</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              account
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">profile</a></li>
              <li><a class="dropdown-item" href="{% url 'trigger1:logout' %}">logout</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>