trigger2/urls.py
from django.urls import path
from trigger2.views import show_pilih_pemain, show_pilih_pelatih, show_mengelola_tim

app_name = 'trigger2'

urlpatterns = [
    path('pilih-pemain/', show_pilih_pemain, name='pilih-pemain'),
    path('pilih-pelatih/', show_pilih_pelatih, name='pilih-pelatih'),
    path('mengelola-tim/', show_mengelola_tim, name='mengelola-tim'),
]

uleague/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('trigger1/', include('trigger1.urls')),
    path('trigger2/', include('trigger2.urls')),
    path('trigger3/', include('trigger3.urls')),
    path('trigger4/', include('trigger4.urls')),
    path('trigger5/', include('trigger5.urls')),
    path('trigger6/', include('trigger6.urls')),
]

trigger2/models.py
from django.db import models

# Create your models here.

trigger2/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
#@login_required(login_url='/sepakbola/login/')
def show_mengelola_tim(request):
    context = {
    }
    return render(request, "mengelola-tim.html", context)

#@login_required(login_url='/sepakbola/login/')
def show_pilih_pemain(request):
    context = {
    }
    return render(request, "pilih-pemain.html", context)

#@login_required(login_url='/sepakbola/login/')
def show_pilih_pelatih(request):
    context = {
    }
    return render(request, "pilih-pelatih.html", context)


trigger2/templates/mengelola-tim.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Peminjaman Stadium</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% include 'navbar/navbar-manajer.html' %}
{% endblock meta %}

{% block content %}
<!-- kalau belum ada tim -->
<!-- <section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">

              <div class="mb-md-5 mt-md-4">
                  <h2 class="fw-bold mb-2 text-center">Form Registrasi</h2>
                  <p class="text-black-50 mb-5 text-center">Daftarkan tim yang akan Anda kelola</p>

                  <form method="POST" action="">
                    <div class="form-group">
                      <label for="formGroupNamaTim">Nama Tim</label>
                      <br>
                      <input type="text" class="form-control" id="formGroupNamaTim" placeholder="FC UI">
                    </div>
                    <div class="form-group mt-4">
                      <label for="formGroupNamaUniv">Nama Universitas</label>
                      <br>
                      <input type="text" class="form-control" id="formGroupNamaUniv" placeholder="Universitas Indonesia">
                    </div>
                    <button class="btn btn-outline-secondary mt-5 mx-auto d-block" type="submit" value="Submit">Submit</button>
                  </form>                             
                    
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->

<!-- kalau udah ada tim -->

<section class="vh-100">
    <div class="mask d-flex align-items-center mt-4">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-12 col-lg-12 col-xl-12">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">
                    <h2 class="fw-bold mb-2 text-center">Tim</h2>
              <p class="text-black-50 mb-3 text-center">Tim yang Anda kelola</p>
              <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th colspan="8" class="text-center">UI FC</th>
                  </tr>
                </thead>
                <thead>
                  <tr>
                    <th colspan="8" class="text-center">Pemain</th>
                  </tr>
                </thead>
                  <thead>
                  <tr>
                    <th>Nama Pemain</th>
                    <th>No HP</th>
                    <th>Tanggal Lahir</th>
                    <th>Is Captain</th>
                    <th>Posisi</th>
                    <th>NPM</th>
                    <th>Jenjang</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tr>
                    <td>John Doe</td>
                    <td>08123456789</td>
                    <td>01/01/1990</td>
                    <td>Yes</td>
                    <td>Kiper</td>
                    <td>2106635631</td>
                    <td>S1</td>
                    <td><button type="button" class="btn btn-primary btn-sm">Make Captain</button>
                      <button type="button" class="btn btn-danger btn-sm">Delete</button></td>
                  </tr>
                  <tr>
                    <td>John Doe</td>
                    <td>08123456789</td>
                    <td>01/01/1990</td>
                    <td>No</td>
                    <td>Bek kiri</td>
                    <td>2106635631</td>
                    <td>S1</td>
                    <td><button type="button" class="btn btn-primary btn-sm">Make Captain</button>
                      <button type="button" class="btn btn-danger btn-sm">Delete</button></td>
                  </tr>
                  <tr>
                    <td>John Doe</td>
                    <td>08123456789</td>
                    <td>01/01/1990</td>
                    <td>No</td>
                    <td>Striker</td>
                    <td>2106635631</td>
                    <td>S1</td>
                    <td><button type="button" class="btn btn-primary btn-sm">Make Captain</button>
                      <button type="button" class="btn btn-danger btn-sm">Delete</button></td>
                  </tr>
                <thead>
                  <tr>
                    <th colspan="8" class="text-center">Pelatih</th>
                  </tr>
                </thead>
                <thead>
                  <tr>
                    <th>Nama Pelatih</th>
                    <th>No HP</th>
                    <th>Email</th>
                    <th colspan="3">Alamat</th>
                    <th>Spesialisasi</th>
                    <th>Action</th>
                  </tr>
                  </thead>
                  <tr>
                    <td>Radit Doe</td>
                    <td>08123456789</td>
                    <td>johndoe@gmail.com</td>
                    <td colspan="3">Jl Beji A2/21 Kota Depok, Jawa Barat</td>
                    <td>Teknik</td>
                    <td>
                      <button type="button" class="btn btn-danger btn-sm">Delete</button></td>
                  </tr>
              </table>
              <p class="text-black-50 mb-3 text-center">Tambahkan Pemain/Pelatih</p>
              <a class="btn btn-outline-secondary" href="{% url 'trigger2:pilih-pelatih' %}" type="button" value="+Pelatih">+ Pelatih</a> 
              <a class="btn btn-outline-secondary" href="{% url 'trigger2:pilih-pemain' %}" type="button" value="+Pemain">+ Pemain</a> 

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% include 'footer.html' %}
  {% endblock content %}

trigger2/templates/pilih-pelatih.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Peminjaman Stadium</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% include 'navbar/navbar-manajer.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">
                    <h2 class="fw-bold mb-2">Pilih Pelatih</h2>
                    <p class="text-black-50 mb-5">Pilih pelatih yang tersedia untuk melatih tim Anda</p>
                      <form method="POST" action="">
                        <div class="form-group">
                          <select class="form-control" id="pilihPelatih">
                            <option disabled selected value="">Pilih pelatih yang ingin didaftarkan</option>                            
                            <option>John Doe - Taktik</option>
                            <option>Doe John - Teknik</option>
                            <option>Radit A - Teknik</option>
                            <option>Arya DK - Taktik</option>
                            <option>Daffa F - Keduanya</option>
                            <option>Jingga M - Keduanya</option>
                          </select>
                        </div>

                        <!-- pake dropdown styled -->
                        <!-- <div class="dropdown">
                          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdown-button">
                            Pilih pelatih yang ingin didaftarkan
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdown-button">
                            <li><a class="dropdown-item" href="#">John Doe - Taktik</a></li>
                            <li><a class="dropdown-item" href="#">Doe John - Teknik</a></li>
                            <li><a class="dropdown-item" href="#">Radit A - Teknik</a></li>
                            <li><a class="dropdown-item" href="#">Arya DK - Taktif</a></li>
                            <li><a class="dropdown-item" href="#">Daffa F - Keduanya</a></li>
                            <li><a class="dropdown-item" href="#">Jingga M - Keduanya</a></li>
                          </ul>
                        </div> -->
                        <br>
                        <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger2:mengelola-tim' %}" value="kembali">Kembali</a>
                        <button class="btn btn-primary mt-5" type="submit" value="Submit">Submit</button>
                      </form>
                      
                  </div>



                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% include 'footer.html' %}
  {% endblock content %}

trigger2/templates/pilih-pemain.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
    <title>Peminjaman Stadium</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% include 'navbar/navbar-manajer.html' %}
{% endblock meta %}

{% block content %}
<section class="vh-100 bg-image">
    <div class="mask d-flex align-items-center h-100 gradient-custom-3">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-9 col-lg-7 col-xl-6">
            <div class="card" style="border-radius: 15px;">
              <div class="card-body p-5 text-center">

                <div class="mb-md-5 mt-md-4">
                    <h2 class="fw-bold mb-2 text-uppercase">Pilih Pemain</h2>
                    <p class="text-black-50 mb-5">Pilih pemain yang tersedia untuk masuk ke tim Anda</p>
                    <div class="dropdown-center">

                      <form method="POST" action="">
                        <form method="POST" action="">
                          <div class="form-group">
                            <select class="form-control" id="pilihPelatih">
                              <option disabled selected value="">Pilih pemain yang ingin didaftarkan</option>                            
                              <option>John Doe - Kiper</option>
                              <option>Doe John - Bek kiri</option>
                              <option>Radit A - Bek kanan</option>
                              <option>Arya DK - Penyerang</option>
                              <option>Daffa F - Sayap kanan</option>
                              <option>Jingga M - Sayap kiri</option>
                            </select>
                          </div>
                          <br>
                          <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger2:mengelola-tim' %}" value="kembali">Kembali</a>
                        <button class="btn btn-primary mt-5" type="submit" value="Submit">Submit</button>
                      </form>

                        <!-- pake dropdown styled-->
                        <!-- <div class="dropdown">
                          <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false" id="dropdown-button">
                            Pilih pemain yang ingin didaftarkan
                          </button>
                          <ul class="dropdown-menu" aria-labelledby="dropdown-button">
                            <li><a class="dropdown-item" href="#">John Doe - Striker</a></li>
                            <li><a class="dropdown-item" href="#">Doe John - Kiper</a></li>
                            <li><a class="dropdown-item" href="#" >Radit A - Bek kiri</a></li>
                            <li><a class="dropdown-item" href="#">Arya DK - Bek kanan</a></li>
                            <li><a class="dropdown-item" href="#">Daffa F - Striker</a></li>
                            <li><a class="dropdown-item" href="#">Jingga M - Bek kiri</a></li>
                          </ul>
                        </div>
                        <br>
                        <a class="btn btn-outline-secondary mt-5" href="{% url 'trigger2:mengelola-tim' %}" value="kembali">Kembali</a>
                        <button class="btn btn-primary mt-5" type="submit" value="Submit">Submit</button>
                      </form>
                      
                  </div> -->



                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
                    
                   
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  {% include 'footer.html' %}
  {% endblock content %}